name: Bug Report
description: Report Minecraft crashes or unexpected behaviors for loading this mod
title: "[Bug]"
labels: ["bug"]
body:
  # 必填模组名称输入框
  - type: input
    id: module_name
    attributes:
      label: Affected Mod's Name
      description: Specify the exact mod related to this bug
      placeholder: e.g. Croparium, BOP Legacy Reborn
    validations:
      required: true

  - type: textarea
    id: bug_desc
    attributes:
      label: Bug Description
      description: Describe what went wrong clearly
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: 1. xxx\n2. xxx\n3. xxx
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Additional Context (logs, screenshots, versions)
