name: Feature Request
description: Submit suggestions for new features or improvements
title: "[Feature]"
labels: ["enhancement"]
body:
  
  - type: markdown
    attributes:
      value: |
        > Important Notice: This project is maintained solo and I am currently stuck in other priorities. So feature requests will likely not be adopted, though they may still be considered in the more distant future.

  
  - type: input
    id: module_name
    attributes:
      label: Affected Mod Name
      description: Which mod will this new feature apply to?
      placeholder: e.g. Croparium, Croparium: Create
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Detailed feature proposal
    validations:
      required: true

